name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: pdf-extracter-win.exe
            asset_name: pdf-extracter.exe
          - os: macos-latest
            name: pdf-extracter-mac.app
            asset_name: pdf-extracter.app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build
        run: |
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          pyinstaller --onefile --noconsole --clean --name pdf-extracter gui.py
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: dist/${{ matrix.asset_name }}
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build.outputs.asset_name }}
