name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip3 install pyinstaller
      - run: pip3 install -r requirements.txt
      - run: pyinstaller --onefile --noconsole --clean --name pdf-extracter gui.py