name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  draft_release_:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            app: pdf-extracter.exe
            asset_name: pdf-extracter-win.exe
          - os: macos-latest
            app: pdf-extracter.app
            asset_name: pdf-extracter-mac.app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build
        run: |
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          pyinstaller --onefile --noconsole --clean --name pdf-extracter gui.py
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: dist/${{ matrix.app }}
  # release:
  #   name: Release
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: ${{ needs.build.outputs.asset_name }}
